# Generated by Django 5.2.5 on 2025-09-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_total_duration_hours_alter_session_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
