# Generated by Django 5.2.5 on 2025-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_session_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='တစ်ကြိမ်သင်တန်းအတွက် အများဆုံး ကြာချိန် (မိနစ်ဖြင့်)'),
        ),
    ]
