# Generated by Django 5.2.5 on 2025-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_day',
            field=models.IntegerField(default=3, help_text='သင်တန်းတစ်ခုလုံးကြာမြင့်မည့် ရက်အရေအတွက် (ဥပမာ: 3 ရက်)', max_length=100, verbose_name='သင်တန်းကြာမြင့်ချိန် (ရက်)'),
        ),
    ]
