# Generated by Django 5.2.5 on 2025-11-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_duration_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_day',
            field=models.IntegerField(default=3, help_text='သင်တန်းတစ်ခုလုံးကြာမြင့်မည့် ရက်အရေအတွက် (ဥပမာ: 3 ရက်)', verbose_name='သင်တန်းကြာမြင့်ချိန် (ရက်)'),
        ),
    ]
