# Generated by Django 5.2.5 on 2025-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_devicetoken_options_devicetoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
