// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKtNQ5MrJMZB2FOelLqRyB3b9jlw-Fs0',
    appId: '1:532024707456:web:661e46f1bc7ccc08f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    authDomain: 'amk-driving.firebaseapp.com',
    storageBucket: 'amk-driving.firebasestorage.app',
    measurementId: 'G-KLYV4T4JPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodd8GMVJppRFgp1mYMYxT3qblrVcpDFM',
    appId: '1:532024707456:android:e58bace5e09a67e4f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    storageBucket: 'amk-driving.firebasestorage.app',
  );
}
