"""
Django settings for amk_driving_school project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from firebase_admin import credentials # type: ignore
import firebase_admin # type: ignore
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fh*zjvm1^w(#v@gpr(5hrjwr=uoh^c#69m_&&ze!^xon8en+_2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'dashboard.apps.DashboardConfig',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'drf_spectacular',

    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'amk_driving_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amk_driving_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




AUTH_USER_MODEL = "accounts.User"



REST_FRAMEWORK = {
  "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
  "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),

  'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
    ],

  'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_TIMEZONE = "Asia/Yangon"
from celery.schedules import crontab # type: ignore
CELERY_BEAT_SCHEDULE = {
  "teacher-digest-7am": {
    "task": "core.tasks.send_daily_teacher_digest",
    "schedule": crontab(hour=7, minute=0),  # Yangon
  },
  "session-reminders-every-5min": {
    "task": "core.tasks.send_session_reminders",
    "schedule": crontab(minute="*/5"),
  },
}


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": 'Format: **Bearer &lt;access_token&gt;**',
        }
    },
    "USE_SESSION_AUTH": False,
}


CORS_ALLOW_ALL_ORIGINS = True

# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:37599',
#     # အနာဂတ်မှာ တခြား port တွေနဲ့ run ရင်လည်း ဒီ list ထဲမှာ ထပ်ထည့်ပေးနိုင်ပါတယ်
#     # ဥပမာ: 'http://localhost:3000'
# ]



from datetime import timedelta

SIMPLE_JWT = {
    # JWT Token သက်တမ်းများ သတ်မှတ်ခြင်း
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Header Format
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    # Login လုပ်တဲ့အခါ Username ဖြင့် လုပ်နိုင်ရန်
    'USER_ID_FIELD': 'id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}


FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'amk-driving-training-sch-285cb-firebase-adminsdk-fbsvc-65d9b9957b.json')

if os.path.exists(FIREBASE_CREDENTIALS_PATH):
    cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
    firebase_admin.initialize_app(cred)
    print("Firebase Admin SDK initialized successfully.")
else:
    print("WARNING: Firebase Admin SDK NOT initialized. amk-driving-training-sch-285cb-firebase-adminsdk-fbsvc-65d9b9957b.json not found.")


JAZZMIN_SETTINGS = {
    "site_title": "AMK Admin",
    "site_header": "AMK Driving Training School",
    "site_brand": "AMK Driving Training School",
    "site_logo": "../profile_pics/amk.png",
    "login_logo": "",
    "welcome_sign": "Welcome to the AMK",
    "copyright": "hobo custom software",

    "custom_js": "js/fcm_admin_config.js",

    "custom_js": "js/admin_notifications.js",

    "custom_css": "css/admin_notifications.css",

    "show_ui_builder": False,
}
