# Generated by Django 5.2.5 on 2025-11-17 17:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_credit_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ကျန်ရှိသင်တန်းနာရီ'),
        ),
    ]
