// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPPugjniwDxlNecC8VLWIgzMfPlOQZvs',
    appId: '1:766958394314:web:91b5787ec661d5e5bdcd33',
    messagingSenderId: '766958394314',
    projectId: 'amk-driving-training-sch-285cb',
    authDomain: 'amk-driving-training-sch-285cb.firebaseapp.com',
    storageBucket: 'amk-driving-training-sch-285cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlunI_YLQnlkw-2hy7Z9B2wf-kDQJ_wxg',
    appId: '1:766958394314:android:4936a11592eb025bbdcd33',
    messagingSenderId: '766958394314',
    projectId: 'amk-driving-training-sch-285cb',
    storageBucket: 'amk-driving-training-sch-285cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5WTvOkIim8d8CFV4j8-P6RW1kiCtp_w',
    appId: '1:766958394314:ios:1ec67a68db7c8fe7bdcd33',
    messagingSenderId: '766958394314',
    projectId: 'amk-driving-training-sch-285cb',
    storageBucket: 'amk-driving-training-sch-285cb.firebasestorage.app',
    iosBundleId: 'com.example.carapp',
  );
}
