// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKtNQ5MrJMZB2FOelLqRyB3b9jlw-Fs0',
    appId: '1:532024707456:web:e98de525ac30bc85f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    authDomain: 'amk-driving.firebaseapp.com',
    storageBucket: 'amk-driving.firebasestorage.app',
    measurementId: 'G-ZSJT8PYKFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodd8GMVJppRFgp1mYMYxT3qblrVcpDFM',
    appId: '1:532024707456:android:4ac8673acb104f4ef71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    storageBucket: 'amk-driving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8FNC8kctQr39Z_63t-T5QQggaS7yhVio',
    appId: '1:532024707456:ios:8d6ee82d8d1a2be9f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    storageBucket: 'amk-driving.firebasestorage.app',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8FNC8kctQr39Z_63t-T5QQggaS7yhVio',
    appId: '1:532024707456:ios:8d6ee82d8d1a2be9f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    storageBucket: 'amk-driving.firebasestorage.app',
    iosBundleId: 'com.example.drivingSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGKtNQ5MrJMZB2FOelLqRyB3b9jlw-Fs0',
    appId: '1:532024707456:web:d7a33fcf634ee8e0f71965',
    messagingSenderId: '532024707456',
    projectId: 'amk-driving',
    authDomain: 'amk-driving.firebaseapp.com',
    storageBucket: 'amk-driving.firebasestorage.app',
    measurementId: 'G-JCHLDK3LG1',
  );

}